
CREATE TABLE `superhero` (
  `id` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `superhero_name` varchar(255) NOT NULL,
  `main_profile_pic_url` varchar(255) NOT NULL,
  `gender` tinyint(4) NOT NULL,
  `looking_for_gender` tinyint(4) NOT NULL,
  `age` int(11) NOT NULL,
  `looking_for_age_min` int(11) NOT NULL,
  `looking_for_age_max` int(11) NOT NULL,
  `looking_for_distance_max` int(11) NOT NULL,
  `distance_unit` varchar(10) NOT NULL,
  `lat` decimal(10,8) NOT NULL,
  `lon` decimal(11,8) NOT NULL,
  `birthday` varchar(50) NOT NULL,
  `country` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `superpower` varchar(255) NOT NULL,
  `account_type` varchar(255) NOT NULL,
  `firebase_token` varchar(255) DEFAULT NULL,
  `is_deleted` tinyint(4) DEFAULT '0',
  `deleted_at` varchar(255) DEFAULT NULL,
  `is_blocked` tinyint(4) DEFAULT '0',
  `blocked_at` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) DEFAULT NULL,
  `created_at` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;