CREATE TABLE superhero
(
    id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    superhero_name VARCHAR(255) NOT NULL,
    main_profile_pic_url VARCHAR(255) NOT NULL,
    gender TINYINT NOT NULL,
    looking_for_gender TINYINT NOT NULL,
    age INT NOT NULL,
    looking_for_age_min INT NOT NULL,
    looking_for_age_max INT NOT NULL,
    looking_for_distance_max INT NOT NULL,
    distance_unit VARCHAR(10) NOT NULL,
    lat DECIMAL(10, 8) NOT NULL,
    lon DECIMAL(11, 8) NOT NULL,
    birthday VARCHAR(50) NOT NULL,
    country VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    superpower VARCHAR(255) NOT NULL,
    account_type VARCHAR(255) NOT NULL,
    is_deleted TINYINT DEFAULT 0,
    deleted_at VARCHAR(255),
    is_blocked TINYINT DEFAULT 0,
    blocked_at VARCHAR(255),
    updated_at VARCHAR(255),
    created_at VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;